# Generated by Django 5.2 on 2025-12-09 03:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerConnection',
            fields=[
                ('username', models.CharField(max_length=24, primary_key=True, serialize=False, unique=True)),
                ('channel_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('online', 'In lobby'), ('configuring', 'In setup screen'), ('in-game', 'In game room')], default='online', max_length=15)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='GameChallenge',
            fields=[
                ('challenge_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('challenger', models.CharField(db_index=True, max_length=24)),
                ('responder', models.CharField(db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Waiting for response'), ('accepted', 'Challenge accepted'), ('declined', 'Challenge declined'), ('expired', 'Challenge expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['challenger'], name='game_gamech_challen_b0559a_idx'), models.Index(fields=['responder'], name='game_gamech_respond_fa1187_idx'), models.Index(fields=['status'], name='game_gamech_status_403b28_idx')],
                'unique_together': {('challenger', 'responder')},
            },
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('game_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('host', models.CharField(max_length=24)),
                ('opponent', models.CharField(max_length=24)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for players'), ('ready', 'All players ready'), ('started', 'Game in progress'), ('closed', 'Game closed')], default='waiting', max_length=10)),
                ('game_mode', models.CharField(default='default', max_length=10)),
                ('game_options', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['host'], name='game_gamero_host_9fc86d_idx'), models.Index(fields=['opponent'], name='game_gamero_opponen_50c937_idx'), models.Index(fields=['status'], name='game_gamero_status_17b630_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerReadyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24)),
                ('is_ready', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ready_statuses', to='game.gameroom')),
            ],
            options={
                'indexes': [models.Index(fields=['game_id', 'is_ready'], name='game_player_game_id_8f1417_idx')],
                'unique_together': {('game_id', 'username')},
            },
        ),
    ]
