# Generated by Django 5.2 on 2026-02-02 00:35

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='host_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='opponent_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamechallenge',
            name='challenge_id',
            field=models.CharField(default=game.models.generate_uuid, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='game_id',
            field=models.CharField(default=game.models.generate_uuid, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
