# Generated by Django 5.1.7 on 2026-02-06 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_playerconnection_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='state', serialize=False, to='game.gameroom')),
                ('board_state', models.JSONField(default=dict)),
                ('current_turn', models.CharField(max_length=24)),
                ('turn_number', models.PositiveIntegerField(default=1)),
                ('move_history', models.JSONField(default=list)),
                ('player_white', models.CharField(max_length=24)),
                ('player_black', models.CharField(max_length=24)),
                ('winner', models.CharField(blank=True, default='', max_length=24)),
                ('end_reason', models.CharField(blank=True, choices=[('', 'In progress'), ('checkmate', 'Checkmate'), ('resign', 'Resignation'), ('timeout', 'Timeout'), ('draw_agreed', 'Draw by agreement'), ('draw_max_turns', 'Draw by max turns'), ('disconnect', 'Disconnect forfeit')], default='', max_length=20)),
                ('config_snapshot', models.JSONField(default=dict)),
                ('draw_offered_by', models.CharField(blank=True, default='', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['current_turn'], name='game_gamest_current_c4945d_idx'), models.Index(fields=['end_reason'], name='game_gamest_end_rea_66c5e0_idx')],
            },
        ),
    ]
