# Generated by Django 6.0.6 on 2026-07-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_gamestate"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameroom",
            name="custom_config",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="gamestate",
            name="end_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "In progress"),
                    ("elimination", "All enemy units eliminated"),
                    ("resign", "Resignation"),
                    ("timeout", "Timeout"),
                    ("draw_agreed", "Draw by agreement"),
                    ("draw_max_turns", "Draw by max turns"),
                    ("disconnect", "Disconnect forfeit"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
