# Generated by Django 6.0.6 on 2026-07-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_gameroom_custom_config_alter_gamestate_end_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestate",
            name="turn_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
