# Generated by Django 6.0.6 on 2026-07-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_gamestate_turn_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerconnection",
            name="secret",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
