# Generated by Django 6.0.6 on 2026-09-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_playerconnection_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='phase_bank',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('', 'In progress'), ('regicide', 'Commander killed'), ('elimination', 'All enemy units eliminated'), ('points', 'Won on points after Phase 3'), ('overtime', 'Overtime ran out; black wins'), ('resign', 'Resignation'), ('timeout', 'Timeout'), ('draw_agreed', 'Draw by agreement'), ('draw_mutual', 'Both commanders fell together'), ('draw_max_turns', 'Draw by max turns'), ('disconnect', 'Disconnect forfeit')], default='', max_length=20),
        ),
    ]
