# Generated by Django 6.0.6 on 2026-09-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_gamestate_phase_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
