# Generated by Django 6.0.6 on 2026-09-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_gamestate_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDisconnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24)),
                ('channel_name', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField()),
                ('game', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='disconnects',
                    to='game.gameroom',
                )),
            ],
        ),
        migrations.AddConstraint(
            model_name='gamedisconnect',
            constraint=models.UniqueConstraint(
                fields=('game', 'username'),
                name='unique_game_disconnect',
            ),
        ),
        migrations.AddIndex(
            model_name='gamedisconnect',
            index=models.Index(fields=['deadline'], name='game_gamedis_deadline_idx'),
        ),
    ]
