# Generated by Django 6.0.6 on 2026-10-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_playerconnection_name_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamechallenge',
            name='challenger',
            field=models.CharField(db_index=True, max_length=37),
        ),
        migrations.AlterField(
            model_name='gamechallenge',
            name='responder',
            field=models.CharField(db_index=True, max_length=37),
        ),
        migrations.AlterField(
            model_name='gamedisconnect',
            name='username',
            field=models.CharField(max_length=37),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='host',
            field=models.CharField(max_length=37),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='opponent',
            field=models.CharField(max_length=37),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='current_turn',
            field=models.CharField(max_length=37),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='draw_offered_by',
            field=models.CharField(blank=True, default='', max_length=37),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player_black',
            field=models.CharField(max_length=37),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player_white',
            field=models.CharField(max_length=37),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='winner',
            field=models.CharField(blank=True, default='', max_length=37),
        ),
        migrations.AlterField(
            model_name='playerconnection',
            name='username',
            field=models.CharField(max_length=37, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='playerreadystatus',
            name='username',
            field=models.CharField(max_length=37),
        ),
    ]
