# Generated by Django 6.0.6 on 2026-10-07 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_username_tripcodes"),
    ]

    operations = [
        migrations.CreateModel(
            name="TurnDraft",
            fields=[
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="turn_draft",
                        serialize=False,
                        to="game.gamestate",
                    ),
                ),
                ("username", models.CharField(max_length=37)),
                ("turn_number", models.PositiveIntegerField()),
                ("sequence", models.PositiveBigIntegerField()),
                ("commands", models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name="gamestate",
            name="end_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "In progress"),
                    ("regicide", "Commander killed"),
                    ("elimination", "All enemy units eliminated"),
                    ("points", "Won on points after Phase 3"),
                    ("phase_result", "Phase tally loss"),
                    ("overtime", "Overtime ran out; black wins"),
                    ("resign", "Resignation"),
                    ("timeout", "Timeout"),
                    ("draw_agreed", "Draw by agreement"),
                    ("draw_mutual", "Both commanders fell together"),
                    ("draw_max_turns", "Draw by max turns"),
                    ("disconnect", "Disconnect forfeit"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
