# Generated by Django 6.0.6 on 2026-10-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0013_turndraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestate",
            name="ability_state",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
